services:
  db:
    image: postgres:15.3-alpine3.18
    restart: always
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=admin
    ports:
        - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:7.4.2
    ports:
      - '6379:6379'

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge