services:
  fund-app:
    build:
      context: ./fund-app
      dockerfile: ./Dockerfile
    ports:
      - '8080:8080'
      - '8081:8081'
    networks:
      - fund-app-network
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
  db:
    image: postgres:15.3-alpine3.18
    restart: always
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=admin
        - POSTGRES_DB=fund-app
    ports:
        - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - fund-app-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d fund-app" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  redis:
    image: redis:7.4.2
    ports:
      - '6379:6379'
    command: '--requirepass redisPassword'
    volumes:
      - redis_data:/data
    networks:
      - fund-app-network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis_data:

networks:
  fund-app-network:
    driver: bridge